Repository mikepenz/gradle-dependency-submission, pull requests merged in 2022-08, with the labels that each got.

#57 Dependency updates - 2022.08.05
  package-lock.json
  package.json
Labels: dependencies

#71 Added default value for `use-gradlew` to README
  README.md
Labels: other

#76 Introduce automatic build file detection for modules
  .github/workflows/gradle-dependency-submission.yml
  .github/workflows/test.yml
  README.md
  __tests__/process.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  dist/licenses.txt
  gradle-example/app/build.gradle
  gradle-example/build.gradle
  gradle-example/gradle/wrapper/gradle-wrapper.jar
  gradle-example/gradle/wrapper/gradle-wrapper.properties
  gradle-example/gradlew
  gradle-example/gradlew.bat
  package-lock.json
  package.json
  src/gradle.ts
  src/main.ts
  src/parse.ts
  src/process.ts
  src/utils.ts
Labels: feature

#77 Dependency updates
  package-lock.json
  package.json
Labels: dependencies

#78 Expand testcases with gradle project in root and `gradle` cli instead of `gradlew`
  .github/workflows/test.yml
  .gitignore
  __tests__/parse.test.ts
  __tests__/process.test.ts
  build.gradle
  dist/index.js
  dist/index.js.map
  src/gradle.ts
  src/main.ts
  src/parse.ts
Labels: fix, test

#79 Retrieve project name from `gradle` if not available
  dist/index.js
  dist/index.js.map
  src/gradle.ts
  src/process.ts
Labels: feature

#80 Log `stderr` of `gradle` task on configuration issues
  README.md
  __tests__/process.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  src/gradle.ts
Labels: feature

#82 Introduce different `sub-module-mode` configuration options
  .github/workflows/gradle-dependency-submission.yml
  README.md
  __tests__/elasticoutput.txt
  __tests__/parse.test.ts
  __tests__/process.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  gradle-example/.gitignore
  gradle-example/library-child-1/build.gradle
  gradle-example/library-child-2/build.gradle
  gradle-example/library-parent-parent/build.gradle
  gradle-example/library-parent/build.gradle
  gradle-example/settings.gradle
  src/main.ts
  src/parse.ts
  src/process.ts
Labels: feature

#83 Enhance logging and error handling for Gradle Version checks
  dist/index.js
  dist/index.js.map
  src/gradle.ts
Labels: feature

#84 Introduce new `DEEP` dependency resolution mode - calls the `dependencies` task on every identified sub-module
  .github/workflows/gradle-dependency-submission.yml
  README.md
  dist/index.js
  dist/index.js.map
  src/main.ts
  src/parse.ts
  src/process.ts
Labels: feature

#85 Enhance logging when using `INDIVIDUAL_DEEP` mode
  .github/workflows/gradle-dependency-submission.yml
  dist/index.js
  dist/index.js.map
  src/process.ts
Labels: other

#86 Offer per module build configuration mapping
  .github/workflows/gradle-dependency-submission.yml
  .github/workflows/test.yml
  README.md
  __tests__/process.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  src/gradle.ts
  src/main.ts
  src/process.ts
Labels: feature

#97 Introduce module fallback if none is provided
  README.md
  dist/index.js
  dist/index.js.map
  src/main.ts
Labels: feature
