Repository mikepenz/gradle-dependency-submission, pull requests merged in 2022-09, with the labels that each got.

#106 Improve Gradle version parsing
  src/gradle.ts
Labels: fix

#110 Introduce support to import `buildEnvironment`
  .github/workflows/gradle-dependency-submission.yml
  README.md
  __tests__/expected_build_env_results.ts
  __tests__/expected_dependency_results.ts
  __tests__/parse.test.ts
  __tests__/process.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  src/gradle.ts
  src/main.ts
  src/process.ts
  tsconfig.json
Labels: feature

#111 Dependency updates
  package-lock.json
  package.json
Labels: dependencies

#112 Support dependency submission without configuration filter
  .github/workflows/test.yml
  README.md
  __tests__/expected_dependency_results_unfiltered.ts
  __tests__/process.test.ts
  action.yml
  dist/index.js
  dist/index.js.map
  src/gradle.ts
  src/main.ts
  src/parse.ts
  src/process.ts
Labels: feature
